### ISSUE TITLE
JS files is modified with line-break codes without being edited while running gulp

### ISSUE THREAD

**Issue by cletosji** [sarvesh123/sji-fe-workflow#1]
I have noticed that the .eslintrc file needs this following line of code which will stop unnecessary modification/updating of JS files. When we start the gulp task runner, it automatically updates the JS files, without the file being opened in editor/updated/modified
{
  "extends": "google",
  "rules": {
    // Additional, per-project rules...
    "indent": 2,
    //THIS BELOW LINE IS REQUIRED
    "linebreak-style": 0,
  },
  "parserOptions" : {
    "ecmaVersion": 6
  }
}

Please check if this can resolve the issue.

**Comment by sarveshshejwadkar** [comment]
Don't use git bash
Use Windows CMD 
i updated the repo for fix while commiting files to not convert lf to crlf
add the line "default_line_ending": "unix" in sublime setting
